# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))
from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------s

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
)

pc: ProjectConfig = ProjectConfig(
    project_name = "SFE",
    project_dependencies = [],
    project_debug_with_visual_studio = True,
    project_executable_names = ["main.exe"]
)

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

if cc.compiler_name == "cl":
    cc.compiler_warning_level = "4"
    cc.compiler_disable_specific_warnings = ["4244", "4100", "4458", "4201", "4116"]
else:
    cc.compiler_warning_level = ""
    cc.compiler_disable_specific_warnings = [
        "deprecated", 
        "parentheses", 
        "implicit-fallthrough",
        "unused-variable"
    ]

build_postfix = f"./build_{cc.compiler_name}/{C_BUILD_BUILD_TYPE()}"
inject = []
libs = ["sfe.lib"]

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        glfw_path = "../../Engine/Vendor/glfw/bin/windows/lib-static-ucrt/glfw3dll.lib"  
    else: 
        glfw_path = "../../Engine/Vendor/glfw/bin/windows/lib-mingw-w64/libglfw3dll.a"
        inject += ["-L/ucrt64/lib", "-lassimp"] #hacky but works for now
    
    libs += [
        glfw_path,
        f"../../Engine/Vendor/assimp/bin/windows/assimp-vc143-mtd.lib",
        GET_LIB_FLAG(cc, "Kernel32"),
        GET_LIB_FLAG(cc, "User32"),
        GET_LIB_FLAG(cc, "Gdi32"),
        GET_LIB_FLAG(cc, "OpenGL32"), 
        GET_LIB_FLAG(cc, "Winmm"),
    ]
elif IS_DARWIN():
    inject += ["-Wl,-rpath,@executable_path"]
    libs += [
        f"../../Engine/Vendor/glfw/bin/macos/lib-arm64/libglfw3.a",
        f"../../Engine/Vendor/assimp/bin/macos/libassimp.dylib",
        "-framework OpenGL",
        "-framework Cocoa",
        "-framework IOKit",
        "-framework CoreFoundation",
    ]


procedures_config = {
    "SFE Engine": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = f"sfe.lib",
        source_files = [
            "../../Engine/Core/**/*.cpp",
            "../../Engine/Platform/**/*.cpp",
            "../../Engine/Input/**/*.cpp",
            
            "../../Engine/engine.cpp",
            "../../Engine/application.cpp"
        ],
        additional_libs = [],
        include_paths = [
            "../../Engine/Vendor",
            "../../Engine/Vendor/stb",
            "../../Engine/Vendor/glad/include", 
            "../../Engine/Vendor/glfw",
            "../../Engine/Vendor/assimp/include",
        ],
        compiler_inject_into_args=[]
    ),
    
    "Main": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = f"main.exe",
        source_files = [
            "../../Game/main.cpp",
            "../../Game/game.cpp",
            "../../Engine/Vendor/glad/src/glad.c",
        ],
        additional_libs = libs,
        compile_time_defines=[],
        include_paths = [
            "../../Engine",
            "../../Engine/Vendor",
            "../../Engine/Vendor/stb",
            "../../Engine/Vendor/glad/include", 
            "../../Engine/Vendor/glfw",
            "../../Engine/Vendor/assimp/include",
        ],
        compiler_inject_into_args=[]
    )
}

"""
"Game DLL": ProcedureConfig(
    build_directory = f"./{build_postfix}",
    output_name = f"Game.dll",
    source_files = [
        "../../Game/game.cpp",
    ],
    additional_libs = libs,
    compile_time_defines=[],
    include_paths = [
        "../../Engine",
        "../../Engine/Vendor",
        "../../Engine/Vendor/stb",
        "../../Engine/Vendor/glad/include", 
        "../../Engine/Vendor/glfw",
        "../../Engine/Vendor/assimp/include",
    ],
    compiler_inject_into_args=[],
    on_source_change_recompile=True
),
"""

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()
# ------------------------------------------------------------------------------------

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        COPY_FILE_TO_DIR("./Engine/Vendor/glfw/bin/windows/lib-static-ucrt", "glfw3.dll", build_postfix)
    else:
        COPY_FILE_TO_DIR("./Engine/Vendor/glfw/bin/windows/lib-mingw-w64", "glfw3.dll", build_postfix)
            
    COPY_FILE_TO_DIR("./Engine/Vendor/assimp/bin/windows", "assimp-vc143-mtd.dll", build_postfix)
elif IS_DARWIN():
    COPY_FILE_TO_DIR("./Engine/Vendor/assimp/bin/macos", "libassimp.6.dylib", build_postfix)