# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))

from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# ---------------------------------------------------------------------------------------

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
)

pc: ProjectConfig = ProjectConfig(
    project_name = "SFE",
    project_dependencies = [],
    project_debug_with_visual_studio = True,
    project_executable_names = ["main.exe"]
)

# ---------------------------- COMPILER SELECTION --------------------------------------

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

if cc.compiler_name == "cl":
    cc.compiler_warning_level = "4"
    cc.compiler_disable_specific_warnings = ["4244", "4100", "4458", "4201", "4116"]
else:
    cc.compiler_warning_level = ""
    cc.compiler_disable_specific_warnings = [
        "deprecated",
        "parentheses",
        "implicit-fallthrough",
        "unused-variable"
    ]

# ---------------------------------------------------------------------------------------
ABSOLUTE_ENGINE_ROOT = "./Engine"
ABSOLUTE_ENGINE_VENDOR = "./Engine/Vendor"
ABSOLUTE_GAME_ROOT = "./Game"

BUILD_APPEND = f"build_{cc.compiler_name}/{C_BUILD_BUILD_TYPE()}"
ABSOLUTE_ENGINE_BUILD = f"./Engine/{BUILD_APPEND}"
ABSOLUTE_GAME_BUILD = f"./Game/{BUILD_APPEND}"

ABSOLUTE_GLFW_ROOT = f"{ABSOLUTE_ENGINE_VENDOR}/glfw"
ABSOLUTE_ASSIMP_ROOT = f"{ABSOLUTE_ENGINE_VENDOR}/assimp"
ABSOLUTE_GLAD_ROOT = f"{ABSOLUTE_ENGINE_VENDOR}/glad"
ABSOLUTE_STB_ROOT = f"{ABSOLUTE_ENGINE_VENDOR}/stb"

# ---

RELATIVE_ENGINE_ROOT = "../../../Engine"
RELATIVE_ENGINE_VENDOR = f"{RELATIVE_ENGINE_ROOT}/Vendor"
RELATIVE_GLFW_ROOT = f"{RELATIVE_ENGINE_VENDOR}/glfw"
RELATIVE_ASSIMP_ROOT = f"{RELATIVE_ENGINE_VENDOR}/assimp"
RELATIVE_GLAD_ROOT = f"{RELATIVE_ENGINE_VENDOR}/glad"
RELATIVE_STB_ROOT = f"{RELATIVE_ENGINE_VENDOR}/stb"
RELATIVE_GLM_ROOT = f"{RELATIVE_ENGINE_VENDOR}/glm"
RELATIVE_IMGUI_ROOT = f"{RELATIVE_ENGINE_VENDOR}/imgui"

RELATIVE_GAME_ROOT = "../../../Game"
RELATIVE_GAME_ASSETS_ROOT = "../../Assets"


inject = []
libs = [
    f"{RELATIVE_ENGINE_ROOT}/{BUILD_APPEND}/sfe.lib"
]

# -------------------------------- PLATFORM LIBS ---------------------------------------

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        glfw_lib = f"{RELATIVE_GLFW_ROOT}/bin/windows/lib-static-ucrt/glfw3dll.lib"
    else:
        glfw_lib = f"{RELATIVE_GLFW_ROOT}/bin/windows/lib-mingw-w64/libglfw3dll.a"
        inject += ["-L/ucrt64/lib", "-lassimp"]

    libs += [
        glfw_lib,
        f"{RELATIVE_ASSIMP_ROOT}/bin/windows/assimp-vc143-mtd.lib",
        GET_LIB_FLAG(cc, "Kernel32"),
        GET_LIB_FLAG(cc, "User32"),
        GET_LIB_FLAG(cc, "Gdi32"),
        GET_LIB_FLAG(cc, "OpenGL32"),
        GET_LIB_FLAG(cc, "Winmm"),
    ]
elif IS_DARWIN():
    inject += ["-Wl,-rpath,@executable_path"]
    libs += [
        f"{RELATIVE_GLFW_ROOT}/bin/macos/lib-arm64/libglfw3.a",
        f"{RELATIVE_ASSIMP_ROOT}/bin/macos/libassimp.dylib",
        "-framework OpenGL",
        "-framework Cocoa",
        "-framework IOKit",
        "-framework CoreFoundation",
    ]

# ---------------------------------------------------------------------------------------


INCLUDES = [
    f"{RELATIVE_ENGINE_ROOT}",
    f"{RELATIVE_ENGINE_ROOT}/OpenGL",
    f"{RELATIVE_ENGINE_ROOT}/ECS",
    f"{RELATIVE_ENGINE_ROOT}/Scene",
    f"{RELATIVE_ENGINE_ROOT}/Input",
    f"{RELATIVE_ENGINE_ROOT}/Managers",

    f"{RELATIVE_ENGINE_VENDOR}",
    f"{RELATIVE_STB_ROOT}",
    f"{RELATIVE_GLM_ROOT}",
    f"{RELATIVE_GLFW_ROOT}",
    f"{RELATIVE_IMGUI_ROOT}",
    f"{RELATIVE_GLAD_ROOT}/include",
    f"{RELATIVE_ASSIMP_ROOT}/include",
]

# ---------------------------------------------------------------------------------------

procedures_config = {
    "SFE Engine": ProcedureConfig(
        build_directory = f"{ABSOLUTE_ENGINE_BUILD}",
        output_name = "sfe.lib",
        source_files = [
            f"{RELATIVE_ENGINE_ROOT}/**/*.cpp",
            f"{RELATIVE_GLAD_ROOT}/src/glad.c",
            f"{RELATIVE_STB_ROOT}/stb_image.c",
        ],
        additional_libs = [],
        compile_time_defines=[f"COMPTIME_ASSERT_ROOT={RELATIVE_GAME_ASSETS_ROOT}"],
        include_paths = INCLUDES,
        compiler_inject_into_args=[]
    ),

    "Main": ProcedureConfig(
        build_directory = f"{ABSOLUTE_GAME_BUILD}",
        output_name = "main.exe",
        source_files = [
            f"{RELATIVE_GAME_ROOT}/*.cpp",
        ],
        additional_libs = libs,
        compile_time_defines=[],
        include_paths = INCLUDES,
        compiler_inject_into_args=inject
    )
}

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()

# -------------------------------- POST BUILD ------------------------------------------

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        COPY_FILE_TO_DIR(f"{ABSOLUTE_GLFW_ROOT}/bin/windows/lib-static-ucrt", "glfw3.dll", ABSOLUTE_GAME_BUILD)
    else:
        COPY_FILE_TO_DIR(f"{ABSOLUTE_GLFW_ROOT}/bin/windows/lib-mingw-w64", "glfw3.dll", ABSOLUTE_GAME_BUILD)

    COPY_FILE_TO_DIR(f"{ABSOLUTE_ASSIMP_ROOT}/bin/windows", "assimp-vc143-mtd.dll", ABSOLUTE_GAME_BUILD)
elif IS_DARWIN():
    COPY_FILE_TO_DIR(f"{ABSOLUTE_ASSIMP_ROOT}/bin/macos", "libassimp.6.dylib", ABSOLUTE_GAME_BUILD)